BAT: 0.1
BLAZE: 0.1
CAVE_SPIDER: 0.1
CHICKEN: 0.1
COW: 0.1
CREEPER: 0.1
ENDERMAN: 0.1
GHAST: 0.1
GIANT: 0.1
HORSE: 0.1
IRON_GOLEM: 0.1
MAGMA_CUBE: 0.1
MUSHROOM_COW: 0.1
OCELOT: 0.1
PIG: 0.1
PIG_ZOMBIE: 0.1
SHEEP: 0.1
SILVERFISH: 0.1
SKELETON: 0.1
SLIME: 0.1
SNOWMAN: 0.1
SPIDER: 0.1
SQUID: 0.1
VILLAGER: 0.1
WITCH: 0.1
WOLF: 0.1
ZOMBIE: 0.1